services:
  db:
    build: .\src\main\resources\db\
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - app_network
  java_app:
    build: .
    container_name: java_app
    ports:
      - "8080:8080"
    environment:
      - GREETING_TEXT=Docker
    networks:
      - app_network
    depends_on:
      - db
networks:
  app_network: {}